LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

DRIVER_SRC_BASE:= $(LOCAL_PATH)
ANDROID_ROOT:= $(CURDIR)

# As we use external compilation to build the kernel we need to use the kernel
# objects directory to build the module. For the module 'clean' rule the kernel
# source directory is enough.
LINUXPATH_SRC = $(ANDROID_ROOT)/kernel_imx
LINUXPATH_OBJ = $(ANDROID_ROOT)/$(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ
CROSS_COMPILE = $(ANDROID_TOOLCHAIN)/arm-linux-androideabi-

KERNEL_PATH = $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ
KERNEL_SRC = $(KERNEL_PATH)

mod_cleanup := $(ANDROID_ROOT)/$(DRIVER_SRC_BASE)/dummy

$(mod_cleanup) :
	$(MAKE) -C $(DRIVER_SRC_BASE) ARCH=arm CROSS_COMPILE=$(CROSS_COMPILE) clean

qca6564_module_file := wlan.ko
$(DRIVER_SRC_BASE)/$(qca6564_module_file): kernelimage $(ACP)
	KERNEL_PATH=$(KERNEL_PATH) KERNEL_SRC=$(KERNEL_SRC) $(MAKE) ARCH=arm -C $(DRIVER_SRC_BASE) CROSS_COMPILE=$(CROSS_COMPILE) MAKEFLAGS= CONFIG_CLD_HL_SDIO_CORE=y CONFIG_LINUX_QCMBR=y WLAN_OPEN_SOURCE=1 MODNAME=wlan CONFIG_QCA_WIFI_ISOC=0 CONFIG_QCA_WIFI_2_0=1 CONFIG_QCA_CLD_WLAN=m WLAN_OPEN_SOURCE=1 CONFIG_NON_QC_PLATFORM=y BUILD_DEBUG_VERSION=0 KBUILD_OPTIONS=WLAN_ROOT=$(ANDROID_ROOT)/$(DRIVER_SRC_BASE)

qca6564_clean: $(mod_cleanup)

include $(CLEAR_VARS)
LOCAL_MODULE := wlan.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_COPY_OUT_VENDOR)/lib/modules
LOCAL_SRC_FILES := $(qca6564_module_file)
include $(BUILD_PREBUILT)
